curso_rails/config/routes.rb
Rails.application.routes.draw do
  root 'home#index' #rota principal

  get 'home/index'

  resources :phones
  resources :addresses #, only [:new, :edit] # apenas rotas com ação 'new' e 'edit'
  resources :contacts #, except [:edit] #todas rotas exceto a edit
  resources :kinds # cria 8 rotas de forma automática

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

curso_rails/app/models/address.rb
class Address < ApplicationRecord
  belongs_to :contact
end

curso_rails/app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :kind #singular
  has_one :address, dependent: :delete #singular
  has_many :phones, dependent: :delete_all #plural

  #atributos aninhados
  #formulario contato pode receber atributos de endereço
  accepts_nested_attributes_for :address 
  accepts_nested_attributes_for :phones, reject_if: :all_blank, allow_destroy: true  #plural pq é has_manny

  validates :name, presence: true, length: { minimum: 3}
  validates :email, presence: true
end

curso_rails/app/models/kind.rb
class Kind < ApplicationRecord
    has_many :contacts #plural
end

curso_rails/app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :contact
end

curso_rails/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :set_options_for_select, only: [:new, :edit, :create, :update]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.order(:name).page(params[:page]).per(15)  #paginacao 
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.build_address
    #options_for_select #chamando método 
  end

  # GET /contacts/1/edit
  def edit
    #options_for_select #chamando método
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_path, notice: I18n.t('messages.created') }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contacts_path, notice:  I18n.t('messages.updated') }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_path, notice:  I18n.t('messages.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    def set_options_for_select
      @kind_options_for_select = Kind.all
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:id, :name, :email, :kind_id, :rmk, 
        address_attributes: [:street, :city, :state, :id],
        phones_attributes: [:id, :phone, :_destroy])
    end
end

curso_rails/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

curso_rails/app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: [:show, :edit, :update, :destroy]

  # GET /kinds
  # GET /kinds.json
  def index # há um view -> com arquivo index
    @meu_nome = "thiago balbino"
    @kinds = Kind.all #SELECT "kinds".* FROM "kinds"
  end

  # GET /kinds/1
  # GET /kinds/1.json
  def show
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds
  # POST /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to @kind, notice: 'Kind was successfully created.' }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1
  # PATCH/PUT /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to @kind, notice: 'Kind was successfully updated.' }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1
  # DELETE /kinds/1.json
  def destroy
    @kind.destroy
    respond_to do |format|
      format.html { redirect_to kinds_url, notice: 'Kind was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind
      @kind = Kind.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kind_params
      params.require(:kind).permit(:description)
    end
end

curso_rails/app/helpers/addresses_helper.rb
module AddressesHelper
end

curso_rails/app/helpers/application_helper.rb
module ApplicationHelper
    def somar_dois(val)
        val + 2
    end
end

curso_rails/app/helpers/contacts_helper.rb
module ContactsHelper
end

curso_rails/app/helpers/home_helper.rb
module HomeHelper
    def mostrar_meu_nome
      "Thiago Henrique"
    end
end

curso_rails/app/helpers/kinds_helper.rb
module KindsHelper
end

curso_rails/app/helpers/phones_helper.rb
module PhonesHelper
end

curso_rails/app/views/contacts/_form.html.erb
<br>
<%= form_with(model: contact, local: true, html: { class: "basic-grey" }) do |form| %>  

  <h1>Contacts</h1>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :contact_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :contact_email %>
  </div>

  <div class="field">
    <%= form.label :kind_id %>    
    <%= form.collection_select(:kind_id, @kind_options_for_select, :id, :description) %>
  </div>


  
  <% #formulário padrão (form) aceita campos aninhados (fields_for) do model (:address) %>
  <%= form.fields_for :address do |address_fields| %>
    <div class="field">
      <%= address_fields.label :street %>    
      <%= address_fields.text_field :street %>
    </div>
    <div class="field">
      <%= address_fields.label :city %>    
      <%= address_fields.text_field :city %>
    </div>
    <div class="field">
      <%= address_fields.label :state %>          
      <%= address_fields.select :state, options_for_select([["Bahia", "BA"], ["São Paulo", "SP"]], @contact.address.state) %>
    </div>
  <% end %>


  <div id="phones">            
    <% #formulário padrão (form) aceita campos aninhados (fields_for) do model (:phones) %>
    <%= form.fields_for :phones do |phones_fields| %>       
        <%= render 'phone_fields', f: phones_fields %>        
    <% end %>

    
    <div class="field">
      <%= form.label :phones, ">" %>
      <%= link_to_add_association('[Adicionar Telefone]', form, :phones) %>  
    </div>
  </div>



  <div class="field">
    <%= form.label :rmk %>
    <%= form.text_area :rmk, id: :contact_rmk %>
  </div>

  <div class="actions">
    <%= form.submit t('buttons.save'), class: "btn btn-primary"   %>  
    <%= link_to t('buttons.back'), contacts_path, class: "btn btn-success"  %>
  </div>



  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= "#{pluralize(contact.errors.count, 'error')} #{t('messages.errors')}:" %></h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% end %>

curso_rails/app/views/contacts/_phone_fields.html.erb
<div class="nested-fields">        
    <div class="field">
        <%= f.label :phone %><br>    
        <%= f.text_field :phone, class: "phone-field" %>
        <%= link_to_remove_association('remover', f) %>    
    </div>      
</div>

curso_rails/app/views/contacts/edit.html.erb
<%= render 'form', contact: @contact %>

curso_rails/app/views/contacts/index.html.erb
<div class="basic-grey">   

  <script>
    $.notify('<%= notice %>', "success");
  </script>
  

  <h1> <%= "#{t('messages.listing')} #{@contacts.model_name.human(count: @contacts.count)}" %></h1>

  <table>
    <thead>
      <tr>
        <th> <%=  @contacts.model.human_attribute_name("name") %></th>        
        <th> <%=  @contacts.model.human_attribute_name("kind") %></th>        
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @contacts.each do |contact| %>
        <tr style="background-color: <%= cycle('white', '#f0f0f5')%>" >
          <td><%= contact.name %></td>          
          <td><%= contact.kind.description %></td>                  
          <td><%= link_to t('buttons.edit'), edit_contact_path(contact) %></td>
          <td><%= link_to t('buttons.destroy'), contact, method: :delete, data: { confirm: t('messages.confirm') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= paginate @contacts %>

  <br>

  <%= link_to t('buttons.new'), new_contact_path, class: "btn btn-primary" %>
  <%= link_to t('buttons.home'), root_path, class: "btn btn-success" %>
</div>

curso_rails/app/views/contacts/new.html.erb
<%= render 'form', contact: @contact %>

curso_rails/app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @contact.kind %>
</p>

<p>
  <strong>Rmk:</strong>
  <%= @contact.rmk %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

curso_rails/app/views/home/index.html.erb
<br>
<div class="basic-grey">    
    <h1>Seja Bem Vindo!</h1>

    <ul>
        <li> <span class="glyphicon glyphicon-th-list aria-hidden="true""></span> <%= link_to "Tipos", kinds_path %></li>
        <li> <span class="glyphicon glyphicon-phone-alt aria-hidden="true""></span> <%= link_to "Contatos", contacts_path %></li>        
    </ul>
</div>