mod2/escamboapp/config/routes.rb
Rails.application.routes.draw do
    
    get 'backoffice', to: 'backoffice/dashboard#index'
    
    namespace :backoffice do
        resources :send_mail, only: [:edit, :create]
        resources :categories, except: [:show, :destroy]
        resources :admins, except: [:show]
        get 'dashboard', to: 'dashboard#index' #mapeando o acesso      
    end  

    namespace :site do
        get 'home', to: 'home#index' #mapeando o acesso
    end


    devise_for :admins, :skip => [:registrations]
    devise_for :members  

    root 'site/home#index'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

mod2/escamboapp/app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :category
  belongs_to :member

  # paperclip
  has_attached_file :avatar, styles: { medium: "700x400>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  #gem money-rails
  monetize :price_cents
end

mod2/escamboapp/app/models/admin.rb
class Admin < ApplicationRecord
  enum role: [:full_access, :restricted_access]

  #### ESCOPO
  scope :with_full_access, -> { where(role: :full_access)} # '->' lambda
  scope :with_restricted_access, -> { where(role: :restricted_access)} # '->' lambda
  
  # ou
  
  #def self.with_full_access
  #  where(role: :full_access )
  #end
  ###########


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

mod2/escamboapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

mod2/escamboapp/app/models/category.rb
class Category < ApplicationRecord
    validates_presence_of :description 
end

mod2/escamboapp/app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

mod2/escamboapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # incluindo módulo Pundit (gem)
    include Pundit
    # Manages Pundit Errors
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
   
    protect_from_forgery with: :exception

    # Layout
    layout :layout_by_resource

    protected

    def layout_by_resource
        if devise_controller? && resource_name == :admin
            "backoffice_devise"
        else
            "application"
        end
    end


    def user_not_authorized
        flash[:alert] = "Você não está autorizado a executar essa ação."
        redirect_to(request.referrer || root_path)
    end
end

mod2/escamboapp/app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]  
  after_action :verify_authorized, only: [:new, :destroy]
  after_action :verify_policy_scoped, only: :index

  def index
    #@admins = Admin.all 
    #@admins = Admin.with_full_access
    #@admins = Admin.with_restricted_access
    @admins = policy_scope(Admin)
  end


  def new
    @admin = Admin.new 
    authorize @admin #pundit
  end


  def create
    @admin = Admin.new(params_admin)
    if @admin.save 
      redirect_to backoffice_admins_path, notice: "O administrador (#{@admin.email}) foi cadastrado com sucesso!"
    else
      render :new
    end
  end


  def edit    
  end


  def update 
    passwd = params[:admin][:password]
    passwd_conf = params[:admin][:password_confirmation]

    if passwd.blank? && passwd_conf.blank?
      params[:admin].delete(:password)
      params[:admin].delete(:password_confirmation)
    end

    if @admin.update(params_admin)
      AdminMailer.update_email(current_admin, @admin).deliver_now
      redirect_to backoffice_admins_path, notice: "O administrador (#{@admin.email}) foi atualizado com sucesso!"
    else
      render :edit
    end
  end


  def destroy
    authorize @admin
    admin_email = @admin.email

    if @admin.destroy 
      redirect_to backoffice_admins_path, notice: "O administrador (#{admin_email}) foi deletado com sucesso!"
    else 
      render :index
    end
  end


  private

  def set_admin 
    @admin = Admin.find(params[:id])      
  end

  def params_admin
    if @admin.blank? 
      params.require(:admin).permit(:name, :email, :password, :password_confirmation, :role)
    else 
      params.require(:admin).permit(policy(@admin).permitted_attributes)
    end
  end

end

mod2/escamboapp/app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController   
  before_action :set_category, only: [:edit, :update]

  def index
    @categories = Category.all
  end  

  
  def new    
    @category = Category.new 
  end

  
  def create    
    @category = CategoryService.create(params_category)

    unless @category.errors.any?
      redirect_to backoffice_categories_path, notice: "A categoria (#{@category.description}) foi cadastrada com sucesso!"
    else 
      render :new
    end
  end


  def edit      
  end

  def update        
    if @category.update(params_category)
      redirect_to backoffice_categories_path, notice: "A categoria (#{@category.description}) foi atualizada com sucesso!"
    else 
      render :edit
    end 
  end


  private

  def set_category
    @category = Category.find(params[:id])      
  end

  def params_category
    params.require(:category).permit(:description)
  end

end

mod2/escamboapp/app/controllers/backoffice/categories_controller/category_service.rb
class Backoffice::CategoriesController::CategoryService
    attr_accessor :category

    def self.create(params_category)
        @category = Category.new(params_category)

        if @category.valid?
            @category.save!
        end 

        @category
    end

end

mod2/escamboapp/app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController    
  def index
  end
end

mod2/escamboapp/app/controllers/backoffice/send_mail_controller.rb
class Backoffice::SendMailController < ApplicationController

    def edit
        @admin = Admin.find(params[:id])

        respond_to do |format|
            format.js
        end
    end

    def create
        begin 
            AdminMailer.send_message(current_admin, params[:'recipient-text'], params[:'subject-text'], params[:'message-text']).deliver_now            
            @notify_message = "Email enviado com sucesso!"
            @notify_flag = "success"
        rescue 
            @notify_message = "Erro ao enviar email. Tente novamente."
            @notify_flag = "error"
        end

        respond_to do |format|
            format.js
        end
    end

end

mod2/escamboapp/app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
    before_action :authenticate_admin!
  
    layout "backoffice"

    def pundit_user
        current_admin #current_user to Pundit       
    end
end

mod2/escamboapp/app/controllers/site/home_controller.rb
class Site::HomeController < ApplicationController
  layout "site"

  def index    
    @categories = Category.order(:description)
    @ads = Ad.limit(5).order(created_at: :desc)
  end
end

mod2/escamboapp/app/helpers/application_helper.rb
module ApplicationHelper
end

mod2/escamboapp/app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
    OptionsForRoles = Struct.new(:id, :description)

    def options_for_roles
        #opção 1
        #options = []

        #Admin.roles_i18n.each do |key, value|
        #    options.push(OptionsForRoles.new(key, value))
        #end

        #options

        #opção 2 - usando map
        Admin.roles_i18n.map do |key, value|
            OptionsForRoles.new(key, value)
        end
    end

end

mod2/escamboapp/app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

mod2/escamboapp/app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

mod2/escamboapp/app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

mod2/escamboapp/app/helpers/site/home_helper.rb
module Site::HomeHelper
end

mod2/escamboapp/app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

mod2/escamboapp/app/views/backoffice/admins/shared/_form.html.erb
<h1 class="page-header">Administradores</h1>

<% if @admin.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <ul>
            <% @admin.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<div class="panel panel-default"> <!-- begin table -->
    <div class="panel-heading">
        <%= action %>
    </div>

    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="col-lg-6"> 
            <%= form_for([:backoffice, @admin]) do |f| %>
                <div class="form-group">
                    <%= f.label :name %>
                    <%= f.text_field :name, class:"form-control", placeholder:"Nome Administrador" %>
                </div> 

                <div class="form-group">
                    <%= f.label :email %>
                    <%= f.text_field :email, class:"form-control", placeholder:"Ex: teste@teste.com.br" %>
                </div>  

                <% if policy(@admin).edit? %>
                    <div class="form-group">
                        <%= f.label :role %>                    
                        <%= f.collection_radio_buttons :role, options_for_roles, :id, :description do |b| %>
                            <div class="radio">
                                <%= b.label {b.radio_button + b.text} %>
                            </div>
                        <% end %>
                    </div>
                <% end %>

                <div class="form-group">
                    <%= f.label :password %>
                    <%= f.password_field :password, class:"form-control", placeholder:"Senha" %>
                </div>  

                <div class="form-group">
                    <%= f.label :password_confirmation %>
                    <%= f.password_field :password_confirmation, class:"form-control", placeholder:"Confirmação da senha" %>
                </div>  

                <button type="submit" class="btn btn-default">Salvar</button>                
            <% end %>
        </div>
    </div>
    <!-- /.panel-body -->
</div> <!-- end table-->

mod2/escamboapp/app/views/backoffice/admins/shared/_send_mail.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel">New message</h4>
            </div>
            <div class="modal-body">
                <%= form_tag backoffice_send_mail_index_path, remote: true do %>
                    <div class="form-group">
                        <label for="recipient-name" class="control-label">Recipient:</label>                        
                        <%= text_field_tag :'recipient-text', nil, class:"form-control", readonly: "readonly" %>
                    </div>

                    <div class="form-group">
                        <label for="recipient-name" class="control-label">Subject:</label>                        
                        <%= text_field_tag :'subject-text', nil, class:"form-control" %>
                    </div>

                    <div class="form-group">
                        <label for="message-text" class="control-label">Message:</label>                        
                        <%= text_area_tag :'message-text', nil, class:"form-control" %>
                    </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>                
                <%= submit_tag 'Send message', class:"btn btn-primary"%>
            </div>
            <% end %>
        </div>
    </div>
</div>

mod2/escamboapp/app/views/backoffice/admins/shared/_send_mail_modal.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel">New message</h4>
            </div>
            <div class="modal-body">
                <%= form_tag backoffice_send_mail_index_path, remote: true do %>
                    <div class="form-group">
                        <label for="recipient-name" class="control-label">Recipient:</label>                        
                        <%= text_field_tag :'recipient-text', nil, class:"form-control", readonly: "readonly" %>
                    </div>

                    <div class="form-group">
                        <label for="recipient-name" class="control-label">Subject:</label>                        
                        <%= text_field_tag :'subject-text', nil, class:"form-control" %>
                    </div>

                    <div class="form-group">
                        <label for="message-text" class="control-label">Message:</label>                        
                        <%= text_area_tag :'message-text', nil, class:"form-control" %>
                    </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>                
                <%= submit_tag 'Send message', class:"btn btn-primary"%>
            </div>
            <% end %>
        </div>
    </div>
</div>

mod2/escamboapp/app/views/backoffice/categories/edit.html.erb
<%= render partial: "backoffice/categories/shared/form", locals: {action: "Editando Categoria"} %>

mod2/escamboapp/app/views/backoffice/categories/index.html.erb
<h1 class="page-header">CATEGORIAS</h1>

<div class="panel panel-default"> <!-- begin table -->
    <div class="panel-heading">
        Listando Categorias
        <%= link_to  new_backoffice_category_path, class:"btn btn-success btn-circle pull-right", style:"margin-top: -5px" do%>
            <i class="fa fa-plus"></i>
        <% end %>                        
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Descrição</th>          
                        <th></th>                              
                    </tr>
                </thead>
                <tbody>
                    <% @categories.each do |category| %>
                        <tr>
                            <td><%= category.id %></td>
                            <td><%= category.description %></td> 
                            <td style="width: 150px">

                                <%= link_to  edit_backoffice_category_path(category.id), class:"btn btn-primary btn-circle" do %>    
                                    <i class="fa fa-edit"></i>                                                    
                                <% end %>

                                <button type="button" disabled class="btn btn-danger btn-circle"><i class="fa fa-minus"></i>
                                </button>
                            </td>                                       
                        </tr>                                    
                    <% end %>
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>
    <!-- /.panel-body -->
</div> <!-- end table-->

mod2/escamboapp/app/views/backoffice/categories/new.html.erb
<%= render partial: "backoffice/categories/shared/form", locals: {action: "Nova Categoria"} %>

mod2/escamboapp/app/views/backoffice/send_mail/create.js.erb
$(function(){    
    $('#sendMailModal').modal('hide'); 
    $('#subject-text').val(''); 
    $('#message-text').val(''); 
    $.notify('<%= @notify_message %>', "<%= @notify_flag%>")
}); 

mod2/escamboapp/app/views/backoffice/send_mail/edit.js.erb
$(function(){
    $('#recipient-text').val('<%= @admin.email %>');
    $('h4.modal-title').text('Enviar mensagem para <%= @admin.name %>');
    $('#sendMailModal').modal(); 
    $('#sendMailModal').on('shown.bs.modal', function(){
        $('#subject-text').focus();
    });
});

mod2/escamboapp/app/views/layouts/backoffice/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.html">BackOffice - Escamboapp</a>
    </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right">        
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li>
                    <a href="#">
                        <i class="fa fa-user fa-fw"></i> User Profile
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-gear fa-fw"></i> Settings
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <%= link_to destroy_admin_session_path, method: :delete do %>
                        <i class="fa fa-sign-out fa-fw"></i> Sair
                    <% end %>                    
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">                
                <li>
                    <%= link_to backoffice_path do %>
                        <i class="fa fa-dashboard fa-fw"></i> Dashboard
                    <% end %>
                </li>
                <li>
                    <%= link_to backoffice_categories_path do %>
                        <i class="fa fa-th-list fa-fw"></i> Categorias
                    <% end %>
                </li>
                <li>
                    <%= link_to backoffice_admins_index_path do %>
                        <i class="fa fa-users fa-fw"></i> Administradores
                    <% end %>
                </li>
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>

mod2/escamboapp/app/views/layouts/site_shared/_footer.html.erb
<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; EscamboApp <%= Date.today.year %> </p>
    </div>
    <!-- /.container -->
</footer>

mod2/escamboapp/app/views/layouts/site_shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="#">Start Bootstrap</a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" 
                data-target="#navbarResponsive" aria-controls="navbarResponsive" 
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                <a class="nav-link" href="#">Home
                    <span class="sr-only">(current)</span>
                </a>
                </li>
                <li class="nav-item">
                    a class="nav-link" href="#">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Services</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

mod2/escamboapp/app/views/members/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

mod2/escamboapp/app/views/site/home/index.html.erb
<!-- Page Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-3">
            <h1 class="my-4">Categorias</h1>
            <div class="list-group">
                
                <% @categories.each do |category| %>
                    <a href="#" class="list-group-item"><%= category.description %></a>
                <% end %>
                
            </div>
        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">            
            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
                <% @ads.each do |ad| %>
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">
                            <a href="#">
                                <img class="card-img-top" src="http://placehold.it/700x400" alt="">
                                <%= image_tag ad.avatar.url(:medium) %>
                            </a>
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a href="#"><%= truncate(ad.title, length: 20) %></a>
                                </h4>
                                <h5><%= humanized_money_with_symbol ad.price%></h5>
                                <p class="card-text"><%= truncate(ad.description, length: 100) %>></p>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                            </div>
                        </div>
                    </div>
                <% end %>                                
            </div>
            <!-- /.row -->
        </div>
        <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

</div>
<!-- /.container -->